### ISSUE TITLE
Claude Idea

### ISSUE THREAD

**Issue by ssochi** [PuruVJ/macos-preact#129]
Hi PuruVJ,

I recently tried creating a project similar to macos-web, with all the code written by Claude. Claude can easily create a simple app, and I feel this approach is very suitable for developing macos-web type projects. With your reputation, many people could easily get involved.

This is my project, which already has 20+ apps. The project link is: https://github.com/ssochi/MacAIverse

![image](https://github.com/PuruVJ/macos-preact/assets/15121953/f9cd7e33-ea2e-4464-82b1-680cfc5efbc9)

**Comment by PuruVJ** [comment]
Thanks, but not interested
